"""
Django settings for Platzigram project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zt3)4245$1vvgqb&70)l(o4v0us3)=lfru7ddduf^pj_9kdybm'

# SECURITY WARNING: don't run with debug turned on in production!


#hiro nuevo
#DEBUG = True
DEBUG = False



#hiro nuevo
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Local APP
    'posts',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',#gracias a este middleware podemos acceder a los usuarios desde cualquier template 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Platzigram.middleware.ProfileCompletionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',#hiro nuevo

]

ROOT_URLCONF = 'Platzigram.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #Aqui añado la carpeta del template usando path absoluto
        'DIRS': [
            os.path.join(BASE_DIR , 'Templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }, 

    },
]

WSGI_APPLICATION = 'Platzigram.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#
#Esto estaba antes del hiro nuevo 
#
#
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': str(os.path.join(BASE_DIR, "db.sqlite3"))#BASE_DIR / 'db.sqlite3',
#    }
#}


#Hiro nuevo
import dj_database_url
from decouple import config 
#de esta manera de definie un base de datos para los proyectos en produccion
DATABASES={
    'default':dj_database_url.config(
        default = config('DATABASE_URL')
    )
}






"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'nombre_base_de_datos',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

"""


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

#https://docs.djangoproject.com/en/3.1/ref/settings/#static-files



STATIC_URL = '/static/'

#HIRO NUEVO
STATIC_ROOT=os.path.join(BASE_DIR,'staticfiles')



#Nombre de la carpeta static
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
#Para asegurar que la aplicacion pueda encontrar los archivos estaticos


#Nota

#Subiendo este proyrcto a git se tiene que realizar algunas modificaciones 

MEDIA_ROOT= os.path.join(BASE_DIR , 'media')
MEDIA_URL='/media/'

LOGIN_URL='/users/login/'

LOGIN_REDIRECT_URL='/'
LOGOUT_REDIRECT_URL = LOGIN_URL



#  tambien se tiene que instalar whitenoise 
#pues django no puede subir archivos estaticos en produccion

#Esto es para actualizar el archivo
# pip freeze > requierements.txt


#hiro nuevo es para mostrar archivos estaticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'